GET http://localhost:5000/api/contacts
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjQ4ZDg5ZmIxMDM5OTU3M2M2ZDFjYzAwIn0sImlhdCI6MTY4NzA1NjU2NSwiZXhwIjoxNjg3MDkyNTY1fQ.2IDVv9q-QQbM_u8P_kJHSJbDgMcPsB4CvkdXsoicw1M

###
POST http://localhost:5000/api/contacts
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjQ4ZDg5ZmIxMDM5OTU3M2M2ZDFjYzAwIn0sImlhdCI6MTY4NzA1NjU2NSwiZXhwIjoxNjg3MDkyNTY1fQ.2IDVv9q-QQbM_u8P_kJHSJbDgMcPsB4CvkdXsoicw1M
Content-Type: application/json

{
  "name": "Mark Doe",
  "email": "mark.doe@email.com",
  "phone": "+2341237654"
}

###
PUT http://localhost:5000/api/contacts/12345

###
DELETE http://localhost:5000/api/contacts/12345